repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.1 # Use the sha / tag you want to point at
    hooks:
      - id: mypy
        additional_dependencies: [types-PyYAML, types-requests]
        files: ^(tests|examples)/.*\.py$
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.4.5
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
        files: ^(tests|examples)/.*\.py$
      # Run the formatter.
      - id: ruff-format
        files: ^(tests|examples)/.*\.py$
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        files: ^(tests|examples)/.*\.py$
      - id: end-of-file-fixer
        files: ^(tests|examples)/.*\.py$
      - id: check-yaml
        files: ^(tests|examples)/.*\.py$
      - id: check-added-large-files
        files: ^(tests|examples)/.*\.py$
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
    - id: detect-secrets
      exclude: example.secrets
      files: ^(tests|examples)/.*\.py$
  - repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.10
    hooks:
      - id: cmake-format
      - id: cmake-lint
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v14.0.0  # Use the appropriate version
    hooks:
      - id: clang-format
        files: ^src/.*\.(cpp|hpp)$
