name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install build dependencies
      run: sudo apt-get install -y cmake ninja-build

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libopenmpi-dev
        pip install pytest

    - name: Configure CMake
      run: cmake --preset ninja-develop

    - name: Build with CMake
      run: cmake --build --preset ninja-develop

    - name: Run specific test
      run: ctest -R pyginkgo_import_test --test-dir build/Develop

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: build
