name: Trigger GitLab CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  trigger_gitlab_ci:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Trigger GitLab Pipeline
      id: trigger
      env:
        BRANCH: ${{ github.head_ref }}
        SHA: ${{ github.event.pull_request.head.sha  }}
        PR_NUMBER: ${{ github.event.pull_request.number }}    
        PIPE_TRIGGER_TOKEN: ${{ secrets.GITLAB_TOKEN }}
      run: |
        response=$(curl -s -X POST \
          --fail-with-body \
          -F "token=$PIPE_TRIGGER_TOKEN" \
          -F "ref=main" \
          -F "variables[SHA]=$SHA" \
          -F "variables[BRANCH]=$BRANCH" \
          -F "variables[PR]=$PR_NUMBER" \
          https://gitlab.kit.edu/api/v4/projects/175208/trigger/pipeline)
        echo "Response: $response"
        pipeline_id=$(echo $response | jq -r '.id')
        pipeline_url=$(echo $response | jq -r '.web_url')
        if [ "$pipeline_id" == "null" ]; then
          echo "Pipeline ID is null. Check the response for errors."
          exit 1
        fi
        echo "PIPELINE_ID=$pipeline_id" >> $GITHUB_ENV
        echo "PIPELINE_URL=$pipeline_url" >> $GITHUB_ENV
        echo "GitHub SHA: ${{ github.event.pull_request.head.sha  }}"
